---
editor_options: 
  markdown: 
    wrap: 72
---

# Datasets

## Global Datasets

### Fine Root Ecology Database: FRED (compilation)

_Description_: Originally a plant root database but also contains some soil laboratory data 
and soil observations.

- `r emo::ji("closed_book")` Iversen CM, McCormack ML, Baer JK, Powell AS, Chen W, Collins C, Fan Y, Fanin N, Freschet GT, Guo D, Hogan JA, Kou L, Laughlin DC, Lavely E, Liese R, Lin D, Meier IC, Montagnoli A, Roumet C, See CR, Soper F, Terzaghi M, Valverde-Barrantes OJ, Wang C, Wright SJ, Wurzburger N, Zadworny M. (2021). [Fine-Root Ecology Database (FRED): A Global Collection of Root Trait Data with Coincident Site, Vegetation, Edaphic, and Climatic Data, Version 3](https://roots.ornl.gov/). Oak Ridge National Laboratory, TES SFA, U.S. Department of Energy, Oak Ridge, Tennessee, U.S.A.  
- `r emo::ji("link")` Project website: <https://roots.ornl.gov/>  
- `r emo::ji("open_file_folder")` Data download URL: <https://doi.org/10.25581/ornlsfa.014/1459186>  
- `r emo::ji("round_pushpin")` Unique locations: 280  
- `r emo::ji("clipboard")` Unique complete rows: 858  
- `r emo::ji("memo")` Import steps: [chemsprops.FRED](https://gitlab.com/openlandmap/compiled-ess-point-data-sets/-/tree/master/themes/sol/SoilChemDB#fine-root-ecology-database-fred) 


### Global Harmonized Dataset of SOC change under perennial crops (compilation)

_Description_: Soil Organic Carbon data from various publications. Many missing 
years for PREVIOUS SOC and SOIL CHARACTERISTICS.

- `r emo::ji("closed_book")` Ledo, A., Hillier, J., Smith, P. et al. (2019) A global, empirical, harmonised dataset of soil organic carbon changes under perennial crops. Sci Data 6, 57. <https://doi.org/10.1038/s41597-019-0062-1>  
- `r emo::ji("link")` Project website: <https://africap.info/>  
- `r emo::ji("open_file_folder")` Data download URL: <https://doi.org/10.6084/m9.figshare.7637210.v2>  
- `r emo::ji("round_pushpin")` Unique locations: 174  
- `r emo::ji("clipboard")` Unique complete rows: 1526  
- `r emo::ji("memo")` Import steps: [chemsprops.SOCPDB](https://gitlab.com/openlandmap/compiled-ess-point-data-sets/-/tree/master/themes/sol/SoilChemDB#global-harmonized-dataset-of-soc-change-under-perennial-crops) 

### Global Soil Respiration DB (compilation)

_Description_: The database encompasses all published studies that report at least one of the following data measured in the field (not laboratory): annual soil respiration, mean seasonal soil respiration, a seasonal or annual partitioning of soil respiration into its source fluxes, soil respiration temperature response (Q10), or soil respiration at 10 degrees C.

- `r emo::ji("closed_book")` Bond-Lamberty, B. and Thomson, A. (2010). A global database of soil respiration data, Biogeosciences, 7, 1915-1926, <https://doi.org/10.5194/bg-7-1915-2010>  
- `r emo::ji("link")` Project website: <https://github.com/bpbond/srdb/>  
- `r emo::ji("open_file_folder")` Data download URL: <https://github.com/bpbond/srdb/>  
- `r emo::ji("round_pushpin")` Unique locations: 826  
- `r emo::ji("clipboard")` Unique complete rows: 1596  
- `r emo::ji("memo")` Import steps: [chemsprops.SRDB](https://gitlab.com/openlandmap/compiled-ess-point-data-sets/-/tree/master/themes/sol/SoilChemDB#global-soil-respiration-db) 

### HYDROS Soil hydraulic functions of international soils (compilation)

_Description_: Contains a data base of 173 soil hydrological data (raw data) from 71 sites all over the world (Asia, Africa, Australia America and Europe). The samples were mainly collected and measured as part of research projects. The soils cover a wide range of texture classes and dry bulk densities. The data base consists of water retention and unsaturated hydraulic conductivity data.

- `r emo::ji("closed_book")` Schindler, Uwe; Müller, Lothar (2015): [Soil hydraulic functions of
international soils measured with the Extended Evaporation Method (EEM) and the HYPROP device](http://dx.doi.org/10.4228/ZALF.2003.273), Leibniz-Zentrum für Agrarlandschaftsforschung (ZALF) e.V.[doi:10.4228/ZALF.2003.273]  
- `r emo::ji("link")` Project website:   
- `r emo::ji("open_file_folder")` Data download URL: <http://dx.doi.org/10.4228/ZALF.2003.273>  
- `r emo::ji("round_pushpin")` Unique locations: 71  
- `r emo::ji("clipboard")` Unique complete rows: 173  
- `r emo::ji("memo")` Import steps: [chemsprops.HYDROS](https://gitlab.com/openlandmap/compiled-ess-point-data-sets/-/tree/master/themes/sol/SoilHydroDB#hydros) 
 

### ISRIC WISE harmonized soil profile data (compilation)

_Description_: ISRIC-WISE database holds selected site and horizon data for 10,250 soil profiles from 149 countries. Profile data were extracted from a wide range of sources and harmonized with respect to the original (1974) and revised (1988) Legend of the FAO-Unesco Soil Map of the World. Profiles have been described, sampled, and analyzed according to methods and standards in use in the originating countries. WISE was specifically developed for land-related applications at continental and global scales.

- `r emo::ji("closed_book")` Batjes, N.H. (2019). [Harmonized soil profile data for applications at global and continental scales: updates to the WISE database](http://dx.doi.org/10.1111/j.1475-2743.2009.00202.x). Soil Use and Management 5:124-127. DOI:10.1111/j.1475-2743.2009.00202.x  
- `r emo::ji("link")` Project website: <https:/isric.org>  
- `r emo::ji("open_file_folder")` Data download URL: <https://files.isric.org/public/wise/WD-WISE.zip>  
- `r emo::ji("round_pushpin")` Unique locations: 6723  
- `r emo::ji("clipboard")` Unique complete rows: 23278  
- `r emo::ji("memo")` Import steps: [chemsprops.WISE](https://gitlab.com/openlandmap/compiled-ess-point-data-sets/-/tree/master/themes/sol/SoilChemDB#isric-wise-harmonized-soil-profile-data)  

### ISRIC World Soil Reference Collection

_Description_: World Soil Reference Collection comprises about 800 soil profiles 
from over 70 countries with detailed soil profile and environmental data.

- `r emo::ji("closed_book")` Batjes, N. H. (1995). [A homogenized soil data file for global
environmental research: A subset of FAO, ISRIC and NRCS profiles (Version 1.0) (No. 95/10b)](https://www.isric.org/sites/default/files/isric_report_1995_10b.pdf). ISRIC. / Van de Ven, T., & Tempel, P. (1994). [ISIS 4.0: ISRIC Soil Information System: User Manual](https://www.isric.org/sites/default/files/ISRIC_TechPap15b.pdf). ISRIC.  
- `r emo::ji("link")` Project website: <https:/isis.isric.org>  
- `r emo::ji("open_file_folder")` Data download URL: <https:/isis.isric.org>  
- `r emo::ji("round_pushpin")` Unique locations: 785  
- `r emo::ji("clipboard")` Unique complete rows: 5637  
- `r emo::ji("memo")` Import steps: [hydrosprops.ISIS](https://gitlab.com/openlandmap/compiled-ess-point-data-sets/-/tree/master/themes/sol/SoilHydroDB#isric-isis)

### Global Reforestation Opportunity Assessment (GROA) (compilation)

_Description_: These data were assembled by the Nature Conservancy and a team of scientists from 19 institutions to quantify carbon sequestration in naturally regenerating forests around the world.

- `r emo::ji("closed_book")` Cook-Patton, S. C., Leavitt, S. M., Gibbs, D., Harris, N. L., Lister, K., Anderson-Teixeira, K. J., ... & Griscom, B. W. (2020). Mapping carbon accumulation potential from global natural forest regrowth. Nature, 585(7826), 545-550. <https://doi.org/10.1038/s41586-020-2686-x>  
- `r emo::ji("link")` Project website: <https://github.com/forc-db/groa>  
- `r emo::ji("open_file_folder")` Data download URL: <https://doi.org/10.5281/zenodo.3983644>  
- `r emo::ji("round_pushpin")` Unique locations: 1921  
- `r emo::ji("clipboard")` Unique complete rows: 1921   
- `r emo::ji("memo")` Import steps: chemsprops.GROA


### Global ICRAF/ISRIC Soil Spectroscopy Library --- (ICRAF/ISRIC)

_Description_: A Globally Distributed Soil Spectral Library Mid Infrared Diffuse 
Reflectance Spectra. MIR scans for some 785 profiles from the ISRIC World Soil Reference Collection.
The samples are from 58 countries spanning Africa, Asia, Europe, North America, and South America. 
Data available under the CC-BY 4.0 license.

- `r emo::ji("closed_book")` World Agroforestry Centre, (2014). [The ICRAF/ISRIC spectral library](https://worldagroforestry.org/sites/default/files/Description_ICRAF-ISRIC%20Soil%20VNIR%20Spectral%20Library.pdf), Soil-Plant Spectral Diagnostics laboratory, United
Nations Avenue, Nairobi, Kenya.   
- `r emo::ji("link")` Project website: <https://www.worldagroforestry.org/sd/landhealth/soil-plant-spectral-diagnostics-laboratory/soil-spectra-library>  
- `r emo::ji("open_file_folder")` Data download URL: <https://files.isric.org/public/other/ICRAF-ISRICVNIRSoilDatabase.zip>  
- `r emo::ji("round_pushpin")` Unique locations: 785  
- `r emo::ji("clipboard")` Unique complete rows:   
- `r emo::ji("memo")` Import steps: [sslsprops.ICRAF_ISRIC](https://gitlab.com/soilspec4gg)

### Global database of soil saturated hydraulic conductivity measurements --- KSat (compilation) 

_Description_: Contains a total of 13,258 Ksat measurements from 1908 sites were assembled from the published literature.

- `r emo::ji("closed_book")` Gupta, S., Hengl, T., Lehmann, P., Bonetti, S., and Or, D.: (2021) [SoilKsatDB: global database of soil saturated hydraulic conductivity measurements for geoscience applications](https://doi.org/10.5194/essd-13-1593-2021), Earth Syst. Sci. Data, 13, 1593–1612, <https://doi.org/10.5194/essd-13-1593-2021>.   
- `r emo::ji("link")` Project website:   
- `r emo::ji("open_file_folder")` Data download URL: <https://doi.org/10.5281/zenodo.3752721>  
- `r emo::ji("round_pushpin")` Unique locations: 1908  
- `r emo::ji("clipboard")` Unique complete rows:   
- `r emo::ji("memo")` Import steps: [hydrosprops](https://gitlab.com/openlandmap/compiled-ess-point-data-sets/-/tree/master/themes/sol/SoilHydroDB)


### Global database of soil hydraulic properties --- GSHP (compilation) 

_Description_: Contains a total of 15,153 soil water characteristics curve (SWCC) measurements from 2659 sites assembled from the published literature.

- `r emo::ji("closed_book")` Gupta, S., Papritz, A., Lehmann, P., Hengl, T., Bonetti, S., and Or, D., (2020): GSHP: Global soil hydraulic properties database”. Manuscript submitted to Scientific Data.   
- `r emo::ji("link")` Project website: https://github.com/ETHZ-repositories/GSHP-database  
- `r emo::ji("open_file_folder")` Data download URL: <https://doi.org/10.5281/zenodo.5547338>  
- `r emo::ji("round_pushpin")` Unique locations: 2659  
- `r emo::ji("clipboard")` Unique complete rows:   
- `r emo::ji("memo")` Import steps: [GSHP-database](https://github.com/ETHZ-repositories/GSHP-database)


### LandPKS observations

_Description_: Data collected by various people through the LandPKS App for mobile 
phones (crowdsourced). Data is of limited quality and usually no laboratory data is collected and shared.

- `r emo::ji("closed_book")` Herrick, J. E., Urama, K. C., Karl, J. W., Boos, J., Johnson, M. V. V., Shepherd, K. D., ... & Kosnik, C. (2013). [The Global Land-Potential Knowledge System (LandPKS): Supporting Evidence-based, Site-specific Land Use and Management through Cloud Computing, Mobile Applications, and Crowdsourcing](https://doi.org/10.2489/jswc.68.1.5A). Journal of Soil and Water Conservation, 68(1), 5A-12A.  
- `r emo::ji("link")` Project website: <http://portal.landpotential.org>  
- `r emo::ji("open_file_folder")` Data download URL: <http://portal.landpotential.org/#/landpksmap>   
- `r emo::ji("round_pushpin")` Unique locations: 15326  
- `r emo::ji("clipboard")` Unique complete rows: 41644  
- `r emo::ji("memo")` Import steps: [chemsprops.LandPKS](https://gitlab.com/openlandmap/compiled-ess-point-data-sets/-/tree/master/themes/sol/SoilChemDB#landpks-observations) 


### Mangrove forest soil DB (compilation)

_Description_: Point data set used to produce a global map of mangrove forest 
soil carbon at 30 m spatial resolution.

- `r emo::ji("closed_book")` Sanderman, J., Hengl, T., Fiske, G., Solvik, K., Adame, M. F., Benson, L., ... & Duncan, C. (2018). [A global map of mangrove forest soil carbon at 30 m spatial resolution](https://doi.org/10.1088/1748-9326/aabe1c). Environmental Research Letters, 13(5), 055002.  
- `r emo::ji("link")` Project website: <https://www.woodwellclimate.org/research-area/carbon/>  
- `r emo::ji("open_file_folder")` Data download URL: <https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/OCYUIT>  
- `r emo::ji("round_pushpin")` Unique locations: 1568  
- `r emo::ji("clipboard")` Unique complete rows: 7718  
- `r emo::ji("memo")` Import steps: [chemsprops.Mangroves](https://gitlab.com/openlandmap/compiled-ess-point-data-sets/-/tree/master/themes/sol/SoilChemDB#mangrove-forest-soil-db) 


### Remnant native SOC database (compilation)

_Description_: Soil carbon profile data from paired land use comparisons.

- `r emo::ji("closed_book")` Sanderman, J., Hengl, T., & Fiske, G. J. (2017). [Soil carbon debt of 12,000 years of human land use](https://doi.org/10.1073/pnas.1706103114). Proceedings of the National Academy of Sciences, 114(36), 9575-9580.  
- `r emo::ji("link")` Project website: <https://www.woodwellclimate.org/research-area/carbon/>  
- `r emo::ji("open_file_folder")` Data download URL: <https://doi.org/10.7910/DVN/QQQM8V/8MSBNI>  
- `r emo::ji("round_pushpin")` Unique locations: 1604  
- `r emo::ji("clipboard")` Unique complete rows: 224  
- `r emo::ji("memo")` Import steps: [chemsprops.RemnantSOC](https://gitlab.com/openlandmap/compiled-ess-point-data-sets/-/tree/master/themes/sol/SoilChemDB#remnant-native-soc-database) 

### SOils DAta Harmonization database: SoDaH (compilation)

_Description_: SoDaH is built on several network science efforts in the
United States. It's aim is to provide an open-access resource to facilitate and automate further harmonization and synthesis of soil carbon data.

- `r emo::ji("closed_book")` Wieder, W. R., Pierson, D., Earl, S., Lajtha, K., Baer, S., Ballantyne, F., ... & Weintraub, S. (2020). [SoDaH: the SOils DAta Harmonization database, an open-source synthesis of soil data from research networks, version 1.0](https://doi.org/10.5194/essd-2020-195). Earth System Science Data Discussions, 1-19. <https://doi.org/10.5194/essd-2020-195>  
- `r emo::ji("link")` Project website: <https://lter.github.io/som-website>  
- `r emo::ji("open_file_folder")` Data download URL: <https://doi.org/10.6073/pasta/9733f6b6d2ffd12bf126dc36a763e0b4>  
- `r emo::ji("round_pushpin")` Unique locations: 1052  
- `r emo::ji("clipboard")` Unique complete rows: 20383  
- `r emo::ji("memo")` Import steps: [chemsprops.SoDaH](https://gitlab.com/openlandmap/compiled-ess-point-data-sets/-/tree/master/themes/sol/SoilChemDB#soils-data-harmonization-database-sodah) 


### Soil Health DB (compilation)

_Description_: A database for global soil health assessment. Only limited soil properties 
available.

- `r emo::ji("closed_book")` Jian, J., Du, X., & Stewart, R. D. (2020). A database for global soil health assessment. Scientific Data, 7(1), 1-8. <https://doi.org/10.1038/s41597-020-0356-3>.  
- `r emo::ji("link")` Project website: <https://github.com/jinshijian/SoilHealthDB>  
- `r emo::ji("open_file_folder")` Data download URL: <https://github.com/jinshijian/SoilHealthDB>   
- `r emo::ji("round_pushpin")` Unique locations: 88  
- `r emo::ji("clipboard")` Unique complete rows: 120  
- `r emo::ji("memo")` Import steps: [chemsprops.SoilHealthDB](https://gitlab.com/openlandmap/compiled-ess-point-data-sets/-/tree/master/themes/sol/SoilChemDB#soil-health-db) 


### Soil Water Infiltration Global database --- SWIG (compilation)

_Description_: Soil textural information (clay, silt, and sand content) is available for 3842 out of 5023 infiltration measurements.

- `r emo::ji("closed_book")` Rahmati, M., Weihermüller, L., Vanderborght, J., Pachepsky, Y. A.,
Mao, L., Sadeghi, S. H., ... & Toth, B. (2018). [Development and analysis of the Soil Water Infiltration Global database](https://doi.org/10.5194/essd-10-1237-2018). Earth Syst. Sci. Data, 10, 1237–1263.  
- `r emo::ji("link")` Project website:   
- `r emo::ji("open_file_folder")` Data download URL: <https://doi.org/10.1594/PANGAEA.885492>   
- `r emo::ji("round_pushpin")` Unique locations: 88  
- `r emo::ji("clipboard")` Unique complete rows: 120  
- `r emo::ji("memo")` Import steps: [chemsprops.SWIG](https://gitlab.com/openlandmap/compiled-ess-point-data-sets/-/tree/master/themes/sol/SoilHydroDB#swig) 


### UNSODA Unsaturated Soil Hydraulic Database (compilation)

_Description_: The dataset contains measured soil water retention, hydraulic conductivity, and water diffusivity data, as well as pedological information of some 790 soil samples from around the world.

- `r emo::ji("closed_book")` Nemes, Attila; Schaap, Marcel; Leij, Feike J.; Wösten, J. Henk M.
(2015). [UNSODA 2.0: Unsaturated Soil Hydraulic Database. Database and program for indirect methods of estimating unsaturated hydraulic properties](https://data.nal.usda.gov/dataset/unsoda-20-unsaturated-soil-hydraulic-database-database-and-program-indirect-methods-estimating-unsaturated-hydraulic-properties). US Salinity Laboratory - ARS - USDA. <https://doi.org/10.15482/USDA.ADC/1173246>. / Børgesen, C. D., Jacobsen, O. H., Hansen, S., & Schaap, M. G. (2006). Soil hydraulic properties near saturation, an improved conductivity model. Journal of Hydrology, 324(1-4), 40-50. <https://doi.org/10.1016/j.jhydrol.2005.09.014> 
- `r emo::ji("link")` Project website:   
- `r emo::ji("open_file_folder")` Data download URL: [Zip packages](https://data.nal.usda.gov/dataset/unsoda-20-unsaturated-soil-hydraulic-database-database-and-program-indirect-methods-estimating-unsaturated-hydraulic-properties)   
- `r emo::ji("round_pushpin")` Unique locations: 790  
- `r emo::ji("clipboard")` Unique complete rows:   
- `r emo::ji("memo")` Import steps: [hydrosprops.UNSODA](https://gitlab.com/openlandmap/compiled-ess-point-data-sets/-/tree/master/themes/sol/SoilHydroDB#unsoda) 

### Worldwide organic soil carbon and nitrogen data

_Description_: A global point data set with organic soil carbon and nitrogen data. 
Poor spatial location accuracy with error often > 10 km. Bulk density for many points has been 
estimated not measured. Sampling year has not been but literature indicates: 
1965, 1974, 1976, 1978, 1979, 1984. Most of samples come from natural vegetation (undisturbed) areas.

- `r emo::ji("closed_book")` Zinke, P. J., Millemann, R. E., & Boden, T. A. (1986). [Worldwide organic soil carbon and nitrogen data](https://cdiac.ess-dive.lbl.gov/ftp/ndp018/ndp018.pdf). Carbon Dioxide Information Center, Environmental Sciences Division, Oak Ridge National Laboratory.  
- `r emo::ji("link")` Project website: <https://cdiac.ess-dive.lbl.gov/>  
- `r emo::ji("open_file_folder")` Data download URL: <https://dx.doi.org/10.3334/CDIAC/lue.ndp018>  
- `r emo::ji("round_pushpin")` Unique locations: 1712  
- `r emo::ji("clipboard")` Unique complete rows: 3977  
- `r emo::ji("memo")` Import steps: [chemsprops.ISCND](https://gitlab.com/openlandmap/compiled-ess-point-data-sets/-/tree/master/themes/sol/SoilChemDB#worldwide-organic-soil-carbon-and-nitrogen-data) 


## Africa

### Africa soil profiles database (compilation)

_Description_: A compilation of legacy soil profiles from hundreds of profiles. 
Produced for the purpose of the Africa Soil Information Services (AfSIS) project.

- `r emo::ji("closed_book")` Leenaars, J. G., Van Oostrum, A. J. M., & Ruiperez Gonzalez, M. (2014). [Africa soil profiles database version 1.2. A compilation of georeferenced and standardized legacy soil profile data for Sub-Saharan Africa (with dataset)](https://www.isric.org/projects/africa-soil-profiles-database-afsp). Wageningen: ISRIC Report 2014/01.  
- `r emo::ji("link")` Project website: <https://www.isric.org/projects/africa-soil-profiles-database-afsp>  
- `r emo::ji("open_file_folder")` Data download URL: <https://data.isric.org/>   
- `r emo::ji("round_pushpin")` Unique locations: 15630  
- `r emo::ji("clipboard")` Unique complete rows: 60306  
- `r emo::ji("memo")` Import steps: [chemsprops.AfSPDB](https://gitlab.com/openlandmap/compiled-ess-point-data-sets/-/tree/master/themes/sol/SoilChemDB#africa-soil-profiles-database) 

### Africa Soil Information Service (AfSIS1) Soil Chemistry

_Description_: Soil spectroscopy-based soil samples datasets. Produced by World 
Agroforestry Centre (ICRAF), Quantitative Engineering Design (QED), Center for 
International Earth Science Information Network (CIESIN), The International Center 
for Tropical Agriculture (CIAT), Crop Nutrition Laboratory Services (CROPNUTS) and 
Rothamsted Research (RRES) for the purpose of the Africa Soil Information Services (AfSIS) project.
Many more samples have been collected in the period 2010--2018.

- `r emo::ji("closed_book")` Towett, E. K., Shepherd, K. D., Tondoh, J. E., Winowiecki, L. A., Lulseged, T., Nyambura, M., ... & Cadisch, G. (2015). Total elemental composition of soils in Sub-Saharan Africa and relationship with soil forming factors. Geoderma Regional, 5, 157-168. <https://doi.org/10.1016/j.geodrs.2015.06.002>  
- `r emo::ji("link")` Project website: <https://github.com/qedsoftware/afsis-soil-chem-tutorial>  
- `r emo::ji("open_file_folder")` Data download URL: <https://registry.opendata.aws/afsis/>   
- `r emo::ji("round_pushpin")` Unique locations: 929  
- `r emo::ji("clipboard")` Unique complete rows: 4162  
- `r emo::ji("memo")` Import steps: [chemsprops.AfSIS1](https://gitlab.com/openlandmap/compiled-ess-point-data-sets/-/tree/master/themes/sol/SoilChemDB#africa-soil-information-service-afsis-soil-chemistry) 

## Asia

### Northern circumpolar permafrost soil profiles (compilation)

_Description_: Represents parts of Russian Federation and Canada. 
This data set consists of significantly higher soil organic carbon concentrations.

- `r emo::ji("closed_book")` Hugelius, G., Bockheim, J. G., Camill, P., Elberling, B., Grosse, G., Harden, J. W., ... & Michaelson, G. (2013). [A new data set for estimating organic carbon storage to 3 m depth in soils of the northern circumpolar permafrost region](https://doi.org/10.5194/essd-5-393-2013). Earth System Science Data (Online), 5(2).  
- `r emo::ji("link")` Project website: <https://bolin.su.se/data/ncscd/>  
- `r emo::ji("open_file_folder")` Data download URL: <http://dx.doi.org/10.5879/ECDS/00000002>   
- `r emo::ji("round_pushpin")` Unique locations: 410  
- `r emo::ji("clipboard")` Unique complete rows: 7104  
- `r emo::ji("memo")` Import steps: [chemsprops.NCSCD](https://gitlab.com/openlandmap/compiled-ess-point-data-sets/-/tree/master/themes/sol/SoilChemDB#northern-circumpolar-permafrost-soil-profiles) 

## Australia & Oceania

## Europe

### Land Use and Coverage Area frame Survey: LUCAS soil

_Description_: Top-soil samples only (0--20 cm). Currently there are three 
campaigns with LUCAS soil samples: 2009, 2015 and 2018. This is currently the largest 
systematic soil sample dataset for EU.

- `r emo::ji("closed_book")` Orgiazzi, A., Ballabio, C., Panagos, P., Jones, A., & Fernandez-Ugalde, O. (2018). [LUCAS Soil, the largest expandable soil dataset for Europe: a review](https://doi.org/10.1111/ejss.12499). European Journal of Soil Science, 69(1), 140-153.  
- `r emo::ji("link")` Project website: <https://esdac.jrc.ec.europa.eu/content/lucas-2009-topsoil-data>  
- `r emo::ji("open_file_folder")` Data download URL: <https://esdac.jrc.ec.europa.eu/content/lucas-2009-topsoil-data>   
- `r emo::ji("round_pushpin")` Unique locations: 21272  
- `r emo::ji("clipboard")` Unique complete rows: 21272 + 21859  
- `r emo::ji("memo")` Import steps: [chemsprops.LUCAS](https://gitlab.com/openlandmap/compiled-ess-point-data-sets/-/tree/master/themes/sol/SoilChemDB#lucas-soil) 

### GEMAS 2009

_Description_: Geochemical background and threshold for 53 chemical elements in 
European agricultural soil.

- `r emo::ji("closed_book")` Reimann, C., Fabian, K., Birke, M., Filzmoser, P., Demetriades, A., Negrel, P., ... & Anderson, M. (2018). [GEMAS: Establishing geochemical background and threshold for 53 chemical elements in European agricultural soil](https://doi.org/10.1016/j.apgeochem.2017.01.021). Applied Geochemistry, 88, 302-318.  
- `r emo::ji("link")` Project website: <http://gemas.geolba.ac.at/>  
- `r emo::ji("open_file_folder")` Data download URL: <http://gemas.geolba.ac.at/>   
- `r emo::ji("round_pushpin")` Unique locations: 4026  
- `r emo::ji("clipboard")` Unique complete rows: 4131  
- `r emo::ji("memo")` Import steps: [chemsprops.GEMAS](https://gitlab.com/openlandmap/compiled-ess-point-data-sets/-/tree/master/themes/sol/SoilChemDB#gemas) 

## North and Central America

## South America

### Sistema de Informacion de Suelos de Latinoamerica: SISLAC (compilation)

_Description_: A compilation of legacy soil profiles from majority of Latin American 
countries.

- `r emo::ji("closed_book")` Alianza Mundial por el Suelo. 2013. Sistema de Informacion de Suelos de Latinoamerica (SISLAC). <https://hdl.handle.net/10568/49611>  
- `r emo::ji("link")` Project website: <http://www.sislac.org/>  
- `r emo::ji("open_file_folder")` Data download URL: <http://54.229.242.119/sislac/es>  
- `r emo::ji("round_pushpin")` Unique locations: 14606  
- `r emo::ji("clipboard")` Unique complete rows: 49994  
- `r emo::ji("memo")` Import steps: [chemsprops.SISLAC](https://gitlab.com/openlandmap/compiled-ess-point-data-sets/-/tree/master/themes/sol/SoilChemDB#sislac)

### CIFOR peatland points (compilation)

_Description_: Peatland soil measurements (points) from the literature.

- `r emo::ji("closed_book")` Murdiyarso, D., Roman-Cuesta, R. M., Verchot, L. V., Herold, M., Gumbricht, T., Herold, N., & Martius, C. (2017). New map reveals more peat in the tropics (Vol. 189). CIFOR. <https://doi.org/10.17528/cifor/006452>  
- `r emo::ji("link")` Project website: <https://www.cifor.org/>  
- `r emo::ji("open_file_folder")` Data download URL:   
- `r emo::ji("round_pushpin")` Unique locations:   
- `r emo::ji("clipboard")` Unique complete rows: 756  
- `r emo::ji("memo")` Import steps: [chemsprops.Peatlands](https://gitlab.com/openlandmap/compiled-ess-point-data-sets/-/tree/master/themes/sol/SoilChemDB#cifor-peatland-points) 


## National Datasets

### Australia

#### CSIRO National Soil Site Database (compilation)

_Description_: National legacy soil profile dataset. Compiled from various projects.

- `r emo::ji("closed_book")` CSIRO (2020). CSIRO National Soil Site Database. v4. CSIRO. Data Collection. <https://data.csiro.au/collections/collection/CIcsiro:7526v004>.  
- `r emo::ji("link")` Project website: <https://www.csiro.au/en/Do-business/Services/Enviro/Soil-archive>  
- `r emo::ji("open_file_folder")` Data download URL: <https://doi.org/10.25919/5eeb2a56eac12>   
- `r emo::ji("round_pushpin")` Unique locations: 13826  
- `r emo::ji("clipboard")` Unique complete rows: 70791  
- `r emo::ji("memo")` Import steps: [chemsprops.NatSoil](https://gitlab.com/openlandmap/compiled-ess-point-data-sets/-/tree/master/themes/sol/SoilChemDB#csiro-national-soil-site-database) 

### Belgium

#### AARDEWERK-Vlaanderen-2010

_Description_: Legacy soil profile dataset for Flemish Region.

- `r emo::ji("closed_book")` Beckers, V., Jacxsens, P., Van De Vreken, Ph., Van Meirvenne, M., Van Orshoven, J. (2011). Gebruik en installatie van de bodemdatabank AARDEWERK-Vlaanderen-2010. Spatial Applications Division Leuven, Belgium. / Ottoy, S., Beckers, V., Jacxsens, P., Hermy, M., & Van Orshoven, J. (2015). [Multi-level statistical soil profiles for assessing regional soil organic carbon stocks](https://doi.org/10.1016/j.geoderma.2015.04.001). Geoderma, 253, 12-20. <https://doi.org/10.1016/j.geoderma.2015.04.001>  
- `r emo::ji("link")` Project website: <https://www.dov.vlaanderen.be>  
- `r emo::ji("open_file_folder")` Data download URL: <https://www.dov.vlaanderen.be>  
- `r emo::ji("round_pushpin")` Unique locations: 6877 
- `r emo::ji("clipboard")` Unique complete rows: 41310 
- `r emo::ji("memo")` Import steps: [chemsprops.Vlaanderen2010](https://gitlab.com/openlandmap/compiled-ess-point-data-sets/-/tree/master/themes/sol/SoilChemDB#aardewerk-vlaanderen-2010)

### Brazil

#### A National Soil Profile Database for Brazil (compilation)

_Description_: National compilation of representative soil profiles. This dataset has been 
used in FEBR. Data comes primarily from the Radam project (Projeto Radambrasil, 1973–1986).

- `r emo::ji("closed_book")` Cooper, M., Mendes, L. M. S., Silva, W. L. C., & Sparovek, G. (2005). [A national soil profile database for Brazil available to international scientists](https://doi.org/10.2136/sssaj2004.0140). Soil Science Society of America Journal, 69(3), 649-652. <https://doi.org/10.2136/sssaj2004.0140> / Benedetti, M. M., Curi, N., Sparovek, G., Carvalho Filho, A., & Silva, S. H. G. (2011). Updated Brazilian’s georeferenced soil database-an improvement for international scientific information exchanging. Embrapa, 1, 309-332.  
- `r emo::ji("link")` Project website:   
- `r emo::ji("open_file_folder")` Data download URL:    
- `r emo::ji("round_pushpin")` Unique locations: 5086  
- `r emo::ji("clipboard")` Unique complete rows: 10,034  
- `r emo::ji("memo")` Import steps: 

#### Brazilian Soil Spectral Library --- BSSL (compilation)

_Description_: Compilation of SS data from various projects. 

- `r emo::ji("closed_book")` Demattê, J. A., Dotto, A. C., Paiva, A. F., Sato, M. V., Dalmolin, R. S., Maria do Socorro, B., ... & do Couto, H. T. Z. (2019). [The Brazilian Soil Spectral Library (BSSL): A general view, application and challenges](https://doi.org/10.1016/j.geoderma.2019.05.043). Geoderma, 354, 113793. <https://doi.org/10.1016/j.geoderma.2019.05.043>  
- `r emo::ji("link")` Project website: <https://bibliotecaespectral.wixsite.com/english>  
- `r emo::ji("open_file_folder")` Data download URL:   
- `r emo::ji("round_pushpin")` Unique locations:   
- `r emo::ji("clipboard")` Unique complete rows: 50,662  
- `r emo::ji("memo")` Import steps:  


#### Free Brazilian Repository for Open Soil Data --- febr (compilation)

_Description_: Soil legacy data from various projects in Brazil standardized and bind together. 

- `r emo::ji("closed_book")` Samuel-Rosa, A., Dalmolin, R. S. D., Moura-Bueno, J. M., Teixeira, W. G., & Alba, J. M. F. (2020). Open legacy soil survey data in Brazil: geospatial data quality and how to improve it. Scientia Agricola, 77(1). <https://doi.org/10.1590/1678-992x-2017-0430>  
- `r emo::ji("link")` Project website: <https://www.pedometria.org/febr/>  
- `r emo::ji("open_file_folder")` Data download URL: <https://www.pedometria.org/febr/>  
- `r emo::ji("round_pushpin")` Unique locations: 6098  
- `r emo::ji("clipboard")` Unique complete rows: 7842  
- `r emo::ji("memo")` Import steps: [chemsprops.FEBR](https://gitlab.com/openlandmap/compiled-ess-point-data-sets/-/tree/master/themes/sol/SoilChemDB#febr) 


####  Hydrophysical database for Brazilian soils --- HYBRAS (compilation)

_Description_: Contains hydrophysical data for Brazilian soils that seeks to consolidate water retention and saturated hydraulic conductivity data together with basic soil features and the methods of determination of these hydraulic properties. 

- `r emo::ji("closed_book")` Ottoni, M. V., Ottoni Filho, T. B., Schaap, M. G., Lopes-Assad, M. L. R., & Rotunno Filho, O. C. (2018). [Hydrophysical database for Brazilian soils (HYBRAS) and pedotransfer functions for water retention](http://www.cprm.gov.br/en/Hydrology/Research-and-Innovation/HYBRAS-4208.html). Vadose Zone Journal, 17(1). 
- `r emo::ji("link")` Project website: <http://geosgb.cprm.gov.br/geosgb/>  
- `r emo::ji("open_file_folder")` Data download URL: <http://geosgb.cprm.gov.br/geosgb/downloads_en.html>  
- `r emo::ji("round_pushpin")` Unique locations: 445  
- `r emo::ji("clipboard")` Unique complete rows:   
- `r emo::ji("memo")` Import steps: [hydrosprops.HYBRAS](https://gitlab.com/openlandmap/compiled-ess-point-data-sets/-/tree/master/themes/sol/SoilHydroDB#hybras) 

### Canada 

#### Agriculture and Agri-Food Canada National Pedon Database

_Description_: Complete soil profile database. Legacy soil profiles collected in 
various projects. Over-represents southern parts of Canada / agricultural land.

- `r emo::ji("closed_book")` [Agriculture and Agri-Food Canada National Pedon Database](https://open.canada.ca/data/en/dataset/6457fad6-b6f5-47a3-9bd1-ad14aea4b9e0).  
- `r emo::ji("link")` Project website: <https://open.canada.ca/data/en/>  
- `r emo::ji("open_file_folder")` Data download URL: <https://open.canada.ca/data/en/dataset/6457fad6-b6f5-47a3-9bd1-ad14aea4b9e0>   
- `r emo::ji("round_pushpin")` Unique locations: 3096  
- `r emo::ji("clipboard")` Unique complete rows: 15946  
- `r emo::ji("memo")` Import steps: [chemsprops.NPDB](https://gitlab.com/openlandmap/compiled-ess-point-data-sets/-/tree/master/themes/sol/SoilChemDB#canada-national-pedon-db) 

#### Canadian upland forest soil profile and carbon stocks database

_Description_: Upper and lower limits for horizons can be negative because convention 
in Canada is to start counting soil depth from mineral soil (hence O and similar horizons 
are not counted).

- `r emo::ji("closed_book")` Shaw, C., Hilger, A., Filiatrault, M., & Kurz, W. (2018). [A Canadian upland forest soil profile and carbon stocks database](https://doi.org/10.1002/ecy.2159). Ecology, 99(4), 989-989. <https://doi.org/10.1002/ecy.2159> 
- `r emo::ji("link")` Project website:   
- `r emo::ji("open_file_folder")` Data download URL: [Supplement file](https://esajournals.onlinelibrary.wiley.com/action/downloadSupplement?doi=10.1002%2Fecy.2159&file=ecy2159-sup-0001-DataS1.zip)  
- `r emo::ji("round_pushpin")` Unique locations: 2347  
- `r emo::ji("clipboard")` Unique complete rows: 15162  
- `r emo::ji("memo")` Import steps: [chemsprops.CUFS](https://gitlab.com/openlandmap/compiled-ess-point-data-sets/-/tree/master/themes/sol/SoilChemDB#canadian-upland-forest-soil-profile-and-carbon-stocks-database) 

#### Alberta AESA (Alberta Environmentally Sustainable Agriculture) Soil Quality Benchmark Program

_Description_: Established in 1998 to provide a [monitoring network across Alberta](https://www.alberta.ca/environmentally-sustainable-agriculture-tracking-survey.aspx) for each of the 43 Ecodistricts. Only limited amount of sampling locations (42 benchmark sites) but revisited every year. It reports that only Phosphorous shows significant changes over time, while SOC, total N, pH stay relatively constant across Alberta.

- `r emo::ji("closed_book")` Cathcart, J., Mason, H., Sey, B. Heinz, J. and Cannon, K. (2008). [Nine Years of Soil Quality Data
from the Alberta Benchmark Program](https://open.alberta.ca/publications/spatial-variability-soil-nutrients-selected-aesa-soil-quality-benchmark-sites). Resource Sciences Branch, Alberta Agriculture and Rural Development, Edmonton, Alberta, Canada. 84 pp.   
- `r emo::ji("link")` Project website: <https://open.canada.ca/data/en/>  
- `r emo::ji("open_file_folder")` Data download URL:   
- `r emo::ji("round_pushpin")` Unique locations: 130  
- `r emo::ji("clipboard")` Unique complete rows: 2484  
- `r emo::ji("memo")` Import steps:   

### Chile

#### Chilean Soil Organic Carbon database

_Description_: Soil carbon samples only.

- `r emo::ji("closed_book")` Pfeiffer, M., Padarian, J., Osorio, R., Bustamante, N., Olmedo, G. F., Guevara, M., et al. (2020) [CHLSOC: the Chilean Soil Organic Carbon database, a multi-institutional collaborative effort](https://doi.org/10.5194/essd-12-457-2020). Earth Syst. Sci. Data, 12, 457-468, <https://doi.org/10.5194/essd-12-457-2020>.  
- `r emo::ji("link")` Project website:   
- `r emo::ji("open_file_folder")` Data download URL: <https://doi.org/10.17605/OSF.IO/NMYS3>   
- `r emo::ji("round_pushpin")` Unique locations: 12132  
- `r emo::ji("clipboard")` Unique complete rows: 16371  
- `r emo::ji("memo")` Import steps: [chemsprops.CHLSOC](https://gitlab.com/openlandmap/compiled-ess-point-data-sets/-/tree/master/themes/sol/SoilChemDB#chilean-soil-organic-carbon-database) 

### China (People's Republic of China)

#### China data set of soil properties for land surface modeling

_Description_: National compilation of representative soil profiles. The point data is 
not available publicly.

- `r emo::ji("closed_book")` Shangguan, W., Dai, Y., Liu, B., Zhu, A., Duan, Q., Wu, L., ... & Zhang, Y. (2013). [A China data set of soil properties for land surface modeling](https://doi.org/10.1002/jame.20026). Journal of Advances in Modeling Earth Systems, 5(2), 212-224. <https://doi.org/10.1002/jame.20026>  
- `r emo::ji("link")` Project website: <http://globalchange.bnu.edu.cn/research/data>  
- `r emo::ji("open_file_folder")` Data download URL:    
- `r emo::ji("round_pushpin")` Unique locations: 8979  
- `r emo::ji("clipboard")` Unique complete rows:   
- `r emo::ji("memo")` Import steps:   

#### SOTER soil profiles for China

_Description_: The Soil and Terrain database for China primary data includes also 
representative soil profiles.

- `r emo::ji("closed_book")` Dijkshoorn, K., van Engelen, V., & Huting, J. (2008). [Soil and landform properties for LADA partner countries](https://isric.org/sites/default/files/isric_report_2008_06.pdf). ISRIC report 2008/06 and GLADA report 2008/03, ISRIC --- World Soil Information and FAO, Wageningen.  
- `r emo::ji("link")` Project website: <https://data.isric.org>  
- `r emo::ji("open_file_folder")` Data download URL: <https://files.isric.org/public/soter/CN-SOTER.zip>   
- `r emo::ji("round_pushpin")` Unique locations: 1430  
- `r emo::ji("clipboard")` Unique complete rows: 5105  
- `r emo::ji("memo")` Import steps: [chemsprops.CNSOTER](https://gitlab.com/openlandmap/compiled-ess-point-data-sets/-/tree/master/themes/sol/SoilChemDB#soter-china-soil-profiles) 

### Croatia

#### Croatian Soil Pedon data

_Description_: National legacy soil profile dataset. Somewhat over-represents forest soils.

- `r emo::ji("closed_book")` Martinovic J., (2000) ["Tla u Hrvatskoj"](https://books.google.nl/books?id=k_a2MgAACAAJ), Monografija, Drzavna uprava za zastitu prirode i okolisa, str. 269, Zagreb. ISBN: 9536793059 / Basic F., (2014) ["The Soils of Croatia"](https://books.google.nl/books?id=VbJEAAAAQBAJ). World Soils Book Series, Springer Science & Business Media, 179 pp. ISBN: 9400758154  
- `r emo::ji("link")` Project website: <http://www.haop.hr/>  
- `r emo::ji("open_file_folder")` Data download URL: [Complete document](https://books.google.nl/books?id=k_a2MgAACAAJ)  
- `r emo::ji("round_pushpin")` Unique locations: 2169  
- `r emo::ji("clipboard")` Unique complete rows: 5746  
- `r emo::ji("memo")` Import steps: [chemsprops.bpht](https://gitlab.com/openlandmap/compiled-ess-point-data-sets/-/tree/master/themes/sol/SoilChemDB#croatian-soil-pedon-data) 

### Congo, Democratic Republic of

#### Soil spectral library for central Africa (CASSL)

_Description_: Contains over 1,800 soil samples with total carbon and total N from ten distinct geo-climatic regions throughout the Congo Basin and wider African Great Lakes region. Points are spatially clustered around six core sampling regions.

- `r emo::ji("closed_book")` Summerauer, L., Baumann, P., Ramirez-Lopez, L., Barthel, M., Bauters, M., Bukombe, B., ... & Six, J. (2021). [Filling a key gap: a soil infrared library for central Africa](https://doi.org/10.5194/soil-2020-99). Soil Discussions, 1-28.  
- `r emo::ji("link")` Project website: <https://github.com/laura-summerauer/ssl-central-africa>  
- `r emo::ji("open_file_folder")` Data download URL: <https://doi.org/10.5281/zenodo.4320395>  
- `r emo::ji("round_pushpin")` Unique locations: 920  
- `r emo::ji("clipboard")` Unique complete rows: 1852  
- `r emo::ji("memo")` Import steps:  


### Costa Rica 

#### Soil Profile DB for Costa Rica

_Description_: National legacy soil profile database for Costa Rica.

- `r emo::ji("closed_book")` Mata, R., Vazquez, A., Rosales, A., & Salazar, D. (2012). [Mapa digital de suelos de Costa Rica](http://www.cia.ucr.ac.cr/?page_id=139). Asociacion Costarricense de la Ciencia del Suelo, San Jose, CRC. Escala, 1, 200000.  
- `r emo::ji("link")` Project website: <http://www.cia.ucr.ac.cr>  
- `r emo::ji("open_file_folder")` Data download URL: [zip file](http://www.cia.ucr.ac.cr/wp-content/recursosnaturales/Base%20perfiles%20de%20suelos%20v1.1.rar)   
- `r emo::ji("round_pushpin")` Unique locations: 472  
- `r emo::ji("clipboard")` Unique complete rows: 2042  
- `r emo::ji("memo")` Import steps: [chemsprops.CostaRica](https://gitlab.com/openlandmap/compiled-ess-point-data-sets/-/tree/master/themes/sol/SoilChemDB#soil-profile-db-for-costa-rica) 

### Germany

#### Stocks of organic carbon in German agricultural soils (BZE_LW)

_Description_: For protection of data privacy, the coordinate was randomly generated 
within a radius of 4-km around the planned sampling point. 

- `r emo::ji("closed_book")` Poeplau, C., Jacobs, A., Don, A., Vos, C., Schneider, F., Wittnebel, M., ... & Flessa, H. (2020). [Stocks of organic carbon in German agricultural soils---Key results of the first comprehensive inventory](https://doi.org/10.1002/jpln.202000113). Journal of Plant Nutrition and Soil Science, 183(6), 665-681.  
- `r emo::ji("link")` Project website: <https://www.thuenen.de/de/ak/>  
- `r emo::ji("open_file_folder")` Data download URL: <https://doi.org/10.3220/DATA20200203151139>   
- `r emo::ji("round_pushpin")` Unique locations: 3104  
- `r emo::ji("clipboard")` Unique complete rows: 17187  
- `r emo::ji("memo")` Import steps: [chemsprops.BZE_LW](https://gitlab.com/openlandmap/compiled-ess-point-data-sets/-/tree/master/themes/sol/SoilChemDB#stocks-of-organic-carbon-in-german-agricultural-soils-bze_lw) 

### Ghana

#### National soil profile legacy DB

_Description_: Described in literature but not yet imported to AfSPDB. 

- `r emo::ji("closed_book")` Owusu, S., Yigini, Y., Olmedo, G. F., & Omuto, C. T. (2020). [Spatial prediction of soil organic carbon stocks in Ghana using legacy data](https://doi.org/10.1016/j.geoderma.2019.114008). Geoderma, 360, 114008.  
- `r emo::ji("link")` Project website:   
- `r emo::ji("open_file_folder")` Data download URL:    
- `r emo::ji("round_pushpin")` Unique locations:   
- `r emo::ji("clipboard")` Unique complete rows:   
- `r emo::ji("memo")` Import steps:  


### Israel

#### The National Soil Spectral Library of Israel

_Description_: Compilation of soil spectral data from various projects. 

- `r emo::ji("closed_book")` NA  
- `r emo::ji("link")` Project website: <https://www.modelfarm-aro.org/subject-areas/the-national-soil-spectral-library-of-israel/?lang=en>  
- `r emo::ji("open_file_folder")` Data download URL:   
- `r emo::ji("round_pushpin")` Unique locations:   
- `r emo::ji("clipboard")` Unique complete rows: 4000  
- `r emo::ji("memo")` Import steps:  

### Iran (Islamic Republic of Iran)

#### Iran soil profile DB

_Description_: National legacy soil profile dataset.

- `r emo::ji("closed_book")` Mohammad, H. B. (2000). Soil resources and use potentiality map of Iran. Soil and Water Research Institute, Teheran, Iran. / Dewan, M. L., & Famouri, J. (1964). The soils of Iran. Food and Agriculture Organization of the United Nations.  
- `r emo::ji("link")` Project website:   
- `r emo::ji("open_file_folder")` Data download URL:    
- `r emo::ji("round_pushpin")` Unique locations: 1373  
- `r emo::ji("clipboard")` Unique complete rows: 4759  
- `r emo::ji("memo")` Import steps: [chemsprops.IRANSPDB](https://gitlab.com/openlandmap/compiled-ess-point-data-sets/-/tree/master/themes/sol/SoilChemDB#iran-soil-profile-db) 

### Nigeria

#### Nigeria Legacy soils and National surveys (compilation)

_Description_: Soil profile observation compiled from Nigeria National Legacy data and IITA Project sites. Submitted by Tunrayo Alabi, CGIAR - Consortium for Spatial Information (CGIAR-CSI). Overlaps with the [Africa Soil profiles dataset](https://opengeohub.github.io/SoilSamples/datasets.html#africa).

- `r emo::ji("closed_book")` Leenaars, J. G., Van Oostrum, A. J. M., & Ruiperez Gonzalez, M. (2014). [Africa soil profiles database version 1.2. A compilation of georeferenced and standardized legacy soil profile data for Sub-Saharan Africa (with dataset)](https://www.isric.org/projects/africa-soil-profiles-database-afsp). Wageningen: ISRIC Report 2014/01. / Akpa, S. I., Odeh, I. O., Bishop, T. F., Hartemink, A. E., & Amapu, I. Y. (2016). [Total soil organic carbon and carbon sequestration potential in Nigeria](https://doi.org/10.1016/j.geoderma.2016.02.021). Geoderma, 271, 202-215.  
- `r emo::ji("link")` Project website: <https://www.africageoportal.com>  
- `r emo::ji("open_file_folder")` Data download URL: <https://www.africageoportal.com/datasets/CSI::legacy-soils-and-national-surveys/about>   
- `r emo::ji("round_pushpin")` Unique locations:   
- `r emo::ji("clipboard")` Unique complete rows: 2569  
- `r emo::ji("memo")` Import steps:  

### Namibia

#### A SOTER database for Namibia: NAMSOTER

_Description_: Legacy soil profile dataset.

- `r emo::ji("closed_book")` Coetzee, M. E. (2001). [NAMSOTER, a SOTER database for Namibia](https://edepot.wur.nl/485173). Agroecological Zoning, 458.  
- `r emo::ji("link")` Project website:   
- `r emo::ji("open_file_folder")` Data download URL:    
- `r emo::ji("round_pushpin")` Unique locations: 1014  
- `r emo::ji("clipboard")` Unique complete rows: 2953  
- `r emo::ji("memo")` Import steps: [chemsprops.LandPKS](https://gitlab.com/openlandmap/compiled-ess-point-data-sets/-/tree/master/themes/sol/SoilChemDB#landpks-observations) 

### Switzerland

#### Swiss National Soil Spectral Model Library

_Description_: National SS library. 

- `r emo::ji("closed_book")` Baumann, P., Helfenstein, A., Gubler, A., Keller, A., Meuli, R. G., Wächter, D., ... & Six, J. (2021). [Developing the Swiss soil spectral library for local estimation and monitoring](https://doi.org/10.5194/soil-2020-105). SOIL Discussions, 1-32. <https://doi.org/10.5194/soil-2020-105>  
- `r emo::ji("link")` Project website:   
- `r emo::ji("open_file_folder")` Data download URL:   
- `r emo::ji("round_pushpin")` Unique locations:   
- `r emo::ji("clipboard")` Unique complete rows:   
- `r emo::ji("memo")` Import steps:  

### Russian Federation

#### The Unified State Register of Soil Resources: EGRPR

_Description_: All documentation in Russian only.

- `r emo::ji("closed_book")` Stolbovoy V.S., Molchanov E.N., Sheremet B.V. Morphogenetic basis of the unified state register of soil resources of Russia. Dokuchaev Soil Bulletin. 2016;(86):115-123. <https://doi.org/10.19047/0136-1694-2016-86-115-123>  
- `r emo::ji("link")` Project website:   
- `r emo::ji("open_file_folder")` Data download URL: <http://egrpr.esoil.ru/content/1DB.html>   
- `r emo::ji("round_pushpin")` Unique locations: 802  
- `r emo::ji("clipboard")` Unique complete rows: 4137  
- `r emo::ji("memo")` Import steps: [chemsprops.EGRPR](https://gitlab.com/openlandmap/compiled-ess-point-data-sets/-/tree/master/themes/sol/SoilChemDB#egrpr) 

### USA 

#### National Cooperative Soil Survey Characterization Database

_Description_: National Cooperative Soil Survey Characterization Database is probably 
the most comprehensive and most detailed soil profile dataset in the World. It is continuously 
maintained by the USDA National Cooperative Soil Survey. Data is available under the 
[CC-0 license](https://creativecommons.org/share-your-work/public-domain/cc0/). 

- `r emo::ji("closed_book")` USDA-NRCS, (2016). [General description for NCSS Soil Characterization Data](https://www.nrcs.usda.gov/wps/portal/nrcs/detail/soils/home/?cid=nrcs142p2_053543). USDA, Natural Resources Conservation Service. / O'Geen, A., Walkinshaw, M., & Beaudette, D. (2017). SoilWeb: A multifaceted interface to soil survey information. Soil Science Society of America Journal, 81(4), 853-862. <https://doi.org/10.2136/sssaj2016.11.0386n>  
- `r emo::ji("link")` Project website: <http://ncsslabdatamart.sc.egov.usda.gov/>  
- `r emo::ji("open_file_folder")` Data download URL: <http://ncsslabdatamart.sc.egov.usda.gov/>  
- `r emo::ji("round_pushpin")` Unique locations: 19861  
- `r emo::ji("clipboard")` Unique complete rows: 136011  
- `r emo::ji("memo")` Import steps: [chemsprops.NCSS](https://gitlab.com/openlandmap/compiled-ess-point-data-sets/-/tree/master/themes/sol/SoilChemDB#national-cooperative-soil-survey-characterization-database)  

#### USDA National Soil Survey Center's Kellogg Soil Survey Laboratory --- (NSSC KSSL)

_Description_: MIR spectral library and associated soil characterization database, which now
includes >50,000 MIR spectra collected on soils primarily from the United States. Currently not available publicly for use. 

- `r emo::ji("closed_book")` Seybold, C. A., Ferguson, R., Wysocki, D., Bailey, S., Anderson, J., Nester, B., ... & Thomas, P. (2019). [Application of Mid‐Infrared Spectroscopy in Soil Survey](https://doi.org/10.2136/sssaj2019.06.0205). Soil Science Society of America Journal, 83(6), 1746-1759. <https://doi.org/10.2136/sssaj2019.06.0205> / Sanderman, J., Savage, K., & Dangal, S. R. (2020). Mid‐infrared spectroscopy for prediction of soil health indicators in the United States. Soil Science Society of America Journal, 84(1), 251-261. <https://doi.org/10.1002/saj2.20009>   
- `r emo::ji("link")` Project website: <https://www.nrcs.usda.gov/wps/portal/nrcs/main/soils/research/>  
- `r emo::ji("open_file_folder")` Data download URL:   
- `r emo::ji("round_pushpin")` Unique locations: 61103  
- `r emo::ji("clipboard")` Unique complete rows:   
- `r emo::ji("memo")` Import steps: [sslsprops.KSSL](https://gitlab.com/soilspec4gg)

#### Rapid Carbon Assessment: RaCA

_Description_: Locations of each site have been degraded due to confidentiality and 
only reflect the general position of each site.

- `r emo::ji("closed_book")` Wills, S. et al. (2013) ["Rapid carbon assessment (RaCA) methodology: Sampling and Initial Summary. United States Department of Agriculture."](https://www.nrcs.usda.gov/wps/PA_NRCSConsumption/download?cid=nrcs142p2_052841&ext=pdf) Natural Resources Conservation Service, National Soil Survey Center.  
- `r emo::ji("link")` Project website: <https://www.nrcs.usda.gov/survey/raca/>  
- `r emo::ji("open_file_folder")` Data download URL: <https://www.nrcs.usda.gov/wps/portal/nrcs/detailfull/soils/research/?cid=nrcs142p2_054164>   
- `r emo::ji("round_pushpin")` Unique locations: 6332  
- `r emo::ji("clipboard")` Unique complete rows: 143006  
- `r emo::ji("memo")` Import steps: [chemsprops.RaCa](https://gitlab.com/openlandmap/compiled-ess-point-data-sets/-/tree/master/themes/sol/SoilChemDB#rapid-carbon-assessment-raca) 

#### USGS Geochemical and mineralogical data for soils

_Description_: Systematic geochemical and mineralogical survey of soil horizons analyzed using a consistent set of methods, sample spacing 1 per 1,600 sq km. Data is available under the 
[CC-0 license](https://creativecommons.org/share-your-work/public-domain/cc0/). 

- `r emo::ji("closed_book")` Smith, D.B., Cannon, W.F., Woodruff, L.G., Solano, Federico, Kilburn, J.E., and Fey, D.L., (2013). [Geochemical and mineralogical data for soils of the conterminous United States](http://pubs.usgs.gov/ds/801/). U.S. Geological Survey Data Series 801, 19 p., <http://pubs.usgs.gov/ds/801/> / Smith, D. B., W. F. Cannon, and L. G. Woodruff (2011). [A national-scale geochemical and mineralogical survey of soils of the conterminous United States](https://doi.org/10.1016/j.apgeochem.2011.03.116). Appl. Geochem., 26, S250–S255. <https://doi.org/10.1016/j.apgeochem.2011.03.116>.  
- `r emo::ji("link")` Project website: <https://mrdata.usgs.gov/ds-801/>  
- `r emo::ji("open_file_folder")` Data download URL: <https://mrdata.usgs.gov/ds-801/>  
- `r emo::ji("round_pushpin")` Unique locations: 4857  
- `r emo::ji("clipboard")` Unique complete rows: 9446  
- `r emo::ji("memo")` Import steps: [chemsprops.USGS.NGS](https://gitlab.com/openlandmap/compiled-ess-point-data-sets/-/tree/master/themes/sol/SoilChemDB#national-geochemical-database-soil)  

#### The Forest Inventory and Analysis Database (FIADB)

_Description_: Systematic inventory of forest plots.  

- `r emo::ji("closed_book")` Domke, G. M., Perry, C. H., Walters, B. F., Nave, L. E., Woodall, C. W., & Swanston, C. W. (2017). [Toward inventory‐based estimates of soil organic carbon in forests of the United States](https://doi.org/10.1002/eap.1516). Ecological Applications, 27(4), 1223-1235. <https://doi.org/10.1002/eap.1516/> / Forest Inventory and Analysis, (2014). The Forest Inventory and Analysis Database: Database description and user guide version 6.0.1 for Phase 3. U.S. Department of Agriculture, Forest Service. 182 p. [Online]. Available: <https://www.fia.fs.fed.us/library/database-documentation/>  
- `r emo::ji("link")` Project website: <https://www.fia.fs.fed.us>  
- `r emo::ji("open_file_folder")` Data download URL: <https://apps.fs.usda.gov/fia/datamart/datamart.html>  
- `r emo::ji("round_pushpin")` Unique locations: 5149  
- `r emo::ji("clipboard")` Unique complete rows: 23208  
- `r emo::ji("memo")` Import steps: [chemsprops.FIADB](https://gitlab.com/openlandmap/compiled-ess-point-data-sets/-/tree/master/themes/sol/SoilChemDB#forest-inventory-and-analysis-database)  

## Other datasets

